name: linting, testing and building
run-name: linting, testing and building
on: 
 push:
  branches: [master]
 pull_request:
  branches: [master]
jobs:
 pipeline:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node-version : [17.x]

  steps: 
  - uses: actions/checkout@v2
  - name: Starting Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
       node-version: ${{ matrix.node-version }}
  - name: install modules with --legacy-peer-deps because of loki/storybook7 conflict
    run: npm install --legacy-peer-deps
  - name: build production project
    run: npm run build:prod
  - name: linting typescript
    run: npm run lint:ts
  - name: linting css
    run: npm run lint:scss
  - name: unit testing
    run: npm run test:unit
 